using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Text;
using TileSetCompiler.Creators;
using TileSetCompiler.Extensions;

namespace TileSetCompiler
{
    class ArtifactCompiler : ItemCompiler
    {
        const string _subDirName = "Artifacts";
        const int _lineLength = 6;
        const int _missileLineLength = 7;
        const string _artifactMissingTileType = "Artifact";
        const string _artifactNoDescription = "no base item description";

        public MissingTileCreator MissingArtifactTileCreator { get; set; }

        public ArtifactCompiler(StreamWriter tileNameWriter) : base(_subDirName, tileNameWriter)
        {
            MissingArtifactTileCreator = new MissingTileCreator();
            MissingArtifactTileCreator.TextColor = Color.Purple;
        }

        public override void CompileOne(string[] splitLine)
        {
            if(splitLine.Length < _lineLength)
            {
                throw new Exception(string.Format("Artifact line '{0}' has too few elements.", string.Join(',', splitLine)));
            }

            var type = splitLine[1];
            var name = splitLine[2];
            var desc = splitLine[3];
            var desc2 = splitLine[5];
            var nameOrDesc = name;
            if(!string.IsNullOrWhiteSpace(desc))
            {
                nameOrDesc = desc;
            }
            else if (!string.IsNullOrWhiteSpace(desc2))
            {
                nameOrDesc = desc2;
            }

            if(!_typeSuffix.ContainsKey(type))
            {
                throw new Exception(string.Format("Artifact Type '{0}' unknown. Line: '{1}'.", type, string.Join(',', splitLine)));
            }

            string direction = null;

            if (type == _typeMissile)
            {
                if (splitLine.Length < _missileLineLength)
                {
                    throw new Exception(string.Format("Too few elements in a missile line: '{0}'.", string.Join(',', splitLine)));
                }
                direction = splitLine[6];
                if (!_missileData.ContainsKey(direction))
                {
                    throw new Exception(string.Format("Invalid direction '{0}'. Line: '{1}'.", direction, string.Join(',', splitLine)));
                }
            }

            if (type == _typeMissile)
            {
                //Autogenerate missile icon
                var subDir2 = _typeNormal;
                var fileName = name.ToLower().Replace(" ", "_") + Program.ImageFileExtension;

                if (!_missileData.ContainsKey(direction))
                {
                    throw new Exception(string.Format("_missileData does not contain direction '{0}'.", direction));
                }

                MissileDirection missileDirection = _missileData[direction].Direction;


                string dirPath = Path.Combine(BaseDirectory.FullName, subDir2);
                var relativePath = Path.Combine(_subDirName, subDir2, fileName);
                var filePath = Path.Combine(dirPath, fileName);
                FileInfo file = new FileInfo(filePath);

                var targetSubDir2 = Path.Combine(_typeMissile, name.ToLower().Replace(" ", "_"));
                var targetFileName = name.ToLower().Replace(" ", "_") +
                    _typeSuffix[type] +
                    _missileData[direction].FileSuffix + Program.ImageFileExtension;
                var targetRelativePath = Path.Combine(_subDirName, targetSubDir2, targetFileName);

                bool isTileMissing = false;

                using (var missileBitmap = ItemMissileCreator.CreateMissileFromFile(file, nameOrDesc.ToProperCaseFirst(), missileDirection, out isTileMissing))
                {
                    if (!isTileMissing)
                    {
                        Console.WriteLine("Autogenerated Artifact Missile Tile {0} successfully.", relativePath);
                        WriteTileNameAutogenerationSuccess(relativePath, targetRelativePath, _missileAutogenerateType);
                    }
                    else
                    {
                        Console.WriteLine("Autogenerated Missing Artifact Missile Tile {0}.", relativePath);
                        WriteTileNameAutogenerationError(relativePath, targetRelativePath, _missileAutogenerateType);
                    }
                    DrawImageToTileSet(missileBitmap);
                    IncreaseCurXY();
                }
            }
            else
            {
                var dirPath = Path.Combine(BaseDirectory.FullName, type.ToLower().Replace(" ", "_"));
                var fileName = name.ToLower().Replace(" ", "_") + _typeSuffix[type] + Program.ImageFileExtension;

                var relativePath = Path.Combine(_subDirName, type.ToLower().Replace(" ", "_"), fileName);
                var filePath = Path.Combine(dirPath, fileName);
                FileInfo file = new FileInfo(filePath);
                bool isTileMissing = false;

                if (!Directory.Exists(dirPath))
                {
                    Console.WriteLine("Artifact directory '{0}' not found. Creating Missing Artifact icon.", dirPath);
                    isTileMissing = true;
                    WriteTileNameErrorDirectoryNotFound(relativePath, "Creating Missing Artifact icon.");
                }
                else
                {
                    if (file.Exists)
                    {
                        Console.WriteLine("Compiled Artifact '{0}' successfully.", relativePath);
                        WriteTileNameSuccess(relativePath);
                    }
                    else
                    {
                        Console.WriteLine("File '{0}' not found. Creating Missing Artifact icon.", file.FullName);
                        isTileMissing = true;
                        WriteTileNameErrorFileNotFound(relativePath, "Creating Missing Artifact icon.");
                    }
                }

                if (!isTileMissing)
                {
                    using (var image = new Bitmap(Image.FromFile(file.FullName)))
                    {
                        DrawItemToTileSet(image);
                    }
                }
                else
                {
                    var subType = "";
                    if(type != _typeNormal)
                    {
                        subType = type;
                    }
                    using (var image = MissingArtifactTileCreator.CreateTile(_artifactMissingTileType, subType, nameOrDesc))
                    {
                        DrawImageToTileSet(image);
                    }
                }
                IncreaseCurXY();
            }            
        }
    }
}
